# Generated by Django 3.2.13 on 2022-10-14 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='heritage',
            fields=[
                ('ccbaCpno', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('ccbaPcd1', models.CharField(max_length=2)),
                ('ccbaPcd1Nm', models.TextField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ccbaCtcd', models.CharField(max_length=2)),
                ('ccbaCtcdNm', models.TextField()),
                ('ccbaKdcd', models.CharField(max_length=2)),
                ('ccmaName', models.CharField(max_length=2)),
                ('crltsnoNm', models.TextField()),
                ('ccbaMnm1', models.TextField()),
                ('ccbaMnm2', models.TextField(null=True)),
                ('imageUrl', models.URLField(max_length=100)),
                ('content', models.TextField()),
                ('ccceName', models.TextField(null=True)),
                ('ccbaLcad', models.TextField()),
                ('ccbaAdmin', models.TextField()),
                ('ccbaPoss', models.TextField()),
                ('ccbaAsdt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('writeDT', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField(null=True)),
                ('answered', models.IntegerField(choices=[(1, 'y'), (0, 'n')])),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='routeDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('comment', models.TextField(null=True)),
                ('ccbaCpno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.heritage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.route')),
            ],
        ),
    ]
